In [1]:
import os
import pandas as pd
import urllib
import numpy as np

In [2]:
path = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\soilmoisture\DrButters_data'
os.chdir(path)

csv = (path + r'\csv.csv')
f = open(csv,'w+')

In [6]:
urllib.request.urlretrieve(
    'http://coagmet.colostate.edu/cgi-bin/web_services.pl?type=soilmoisture_hourly&sids=rfd01' + 
    '&sdate=1992-06-04&edate=2018-12-31',filename=csv)

df = pd.read_csv(csv)
df = df.reset_index()
df.columns = ['index','station','datetime','4in_vwc','4in_ec','4in_soiltemp',
             '25in_vwc','24in_ec','24in_soiltemp']
stuff = ['index']
df = df.drop(stuff,axis=1)
df

,station,datetime,4in_vwc,4in_ec,4in_soiltemp,25in_vwc,24in_ec,24in_soiltemp
0,rfd01,2014-06-11 11:00:00,0.447,0.495,23.770,0.310,0.308,21.250
1,rfd01,2014-06-11 12:00:00,0.449,0.502,25.960,0.309,0.309,22.530
2,rfd01,2014-06-11 13:00:00,0.452,0.510,26.440,0.309,0.310,23.560
3,rfd01,2014-06-11 14:00:00,0.453,0.517,26.560,0.309,0.311,23.970
4,rfd01,2014-06-11 15:00:00,0.453,0.519,23.520,0.309,0.311,21.660
5,rfd01,2014-06-11 16:00:00,0.449,0.518,24.980,0.309,0.311,22.410
6,rfd01,2014-06-11 17:00:00,0.441,0.518,23.930,0.309,0.310,22.070
7,rfd01,2014-06-11 18:00:00,0.446,0.515,21.920,0.309,0.309,20.500
8,rfd01,2014-06-11 19:00:00,0.450,0.503,16.870,0.308,0.306,17.100
9,rfd01,2014-06-11 20:00:00,0.448,0.496,15.220,0.308,0.305,15.480
10,rfd01,2014-06-11 21:00:00,0.446,0.492,15.230,0.308,0.304,15.430
11,rfd01,2014-06-11 22:00:00,0.444,0.488,14.570,0.308,0.303,14.870
12,rfd01,2014-06-11 23:00:00,0.442,0.484,14.220,0.307,0.302,14.600
13,rfd01,2014-06-12 00:00:00,0.441,0.480,13.750,0.307,0.301,14.390
14,rfd01,2014-06-12 01:00:00,0.439,0.477,13.890,0.307,0.300,14.570
15,rfd01,2014-06-12 02:00:00,0.437,0.472,13.380,0.306,0.300,14.030
16,rfd01,2014-06-12 03:00:00,0.435,0.470,12.950,0.306,0.299,13.460
17,rfd01,2014-06-12 04:00:00,0.434,0.467,13.610,0.306,0.298,13.950
18,rfd01,2014-06-12 05:00:00,0.432,0.464,13.560,0.305,0.297,14.370
19,rfd01,2014-06-12 06:00:00,0.431,0.462,14.020,0.305,0.297,14.690
20,rfd01,2014-06-12 07:00:00,0.431,0.461,15.070,0.305,0.296,15.320
21,rfd01,2014-06-12 08:00:00,0.430,0.460,17.180,0.304,0.296,16.370
22,rfd01,2014-06-12 09:00:00,0.428,0.465,17.870,0.304,0.296,16.870
23,rfd01,2014-06-12 10:00:00,0.430,0.463,20.060,0.303,0.296,18.200
24,rfd01,2014-06-12 11:00:00,0.430,0.466,22.010,0.303,0.297,19.830
25,rfd01,2014-06-12 12:00:00,0.432,0.472,23.400,0.302,0.298,21.460
26,rfd01,2014-06-12 13:00:00,0.433,0.478,24.040,0.302,0.299,22.920
27,rfd01,2014-06-12 14:00:00,0.435,0.483,24.610,0.302,0.300,23.580
28,rfd01,2014-06-12 15:00:00,0.436,0.488,26.060,0.302,0.300,23.130
29,rfd01,2014-06-12 16:00:00,0.437,0.495,24.470,0.301,0.300,22.290
...,...,...,...,...,...,...,...,...
39826,rfd01,2018-12-29 19:00:00,0.287,0.174,0.869,7999.000,0.168,4.793
39827,rfd01,2018-12-29 20:00:00,0.287,0.174,0.870,7999.000,0.167,4.828
39828,rfd01,2018-12-29 21:00:00,0.287,0.174,0.866,7999.000,0.167,4.800
39829,rfd01,2018-12-29 22:00:00,0.287,0.174,0.845,7999.000,0.167,4.772
39830,rfd01,2018-12-29 23:00:00,0.287,0.174,0.808,7999.000,0.167,4.756
39831,rfd01,2018-12-30 00:00:00,0.287,0.174,0.763,7999.000,0.167,4.734
39832,rfd01,2018-12-30 01:00:00,0.287,0.174,0.723,7999.000,0.167,4.733
39833,rfd01,2018-12-30 02:00:00,0.287,0.173,0.669,7999.000,0.167,4.732
39834,rfd01,2018-12-30 03:00:00,0.286,0.173,0.620,7999.000,0.167,4.732
39835,rfd01,2018-12-30 04:00:00,0.286,0.173,0.586,7999.000,0.167,4.701
39836,rfd01,2018-12-30 05:00:00,0.286,0.173,0.550,7999.000,0.167,4.708
39837,rfd01,2018-12-30 06:00:00,0.286,0.172,0.512,7999.000,0.167,4.682
39838,rfd01,2018-12-30 07:00:00,0.286,0.172,0.479,7999.000,0.167,4.662
39839,rfd01,2018-12-30 08:00:00,0.285,0.172,0.465,7999.000,0.167,4.651
39840,rfd01,2018-12-30 09:00:00,0.285,0.171,0.413,7999.000,0.167,4.667
39841,rfd01,2018-12-30 10:00:00,0.285,0.171,0.384,7999.000,0.167,4.649
39842,rfd01,2018-12-30 11:00:00,0.285,0.171,0.354,7999.000,0.167,4.626
39843,rfd01,2018-12-30 12:00:00,0.284,0.171,0.353,7999.000,0.167,4.619
39844,rfd01,2018-12-30 13:00:00,0.285,0.170,0.370,7999.000,0.167,4.602
39845,rfd01,2018-12-30 14:00:00,0.285,0.170,0.394,7999.000,0.167,4.599
39846,rfd01,2018-12-30 15:00:00,0.285,0.170,0.420,7999.000,0.167,4.593
39847,rfd01,2018-12-30 16:00:00,0.284,0.170,0.446,7999.000,0.166,4.582
39848,rfd01,2018-12-30 17:00:00,0.285,0.170,0.465,7999.000,0.167,4.569
39849,rfd01,2018-12-30 18:00:00,0.285,0.170,0.495,7999.000,0.166,4.562
39850,rfd01,2018-12-30 19:00:00,0.284,0.171,0.518,7999.000,0.166,4.547
39851,rfd01,2018-12-30 20:00:00,0.285,0.171,0.539,7999.000,0.166,4.528
39852,rfd01,2018-12-30 21:00:00,0.285,0.171,0.567,7999.000,0.166,4.534
39853,rfd01,2018-12-30 22:00:00,0.285,0.171,0.572,7999.000,0.166,4.519
39854,rfd01,2018-12-30 23:00:00,0.285,0.171,0.571,7999.000,0.166,4.485
39855,rfd01,2018-12-31 00:00:00,0.285,0.171,0.603,7999.000,0.166,4.478

In [8]:
df['datetime'] = pd.to_datetime(df.datetime,errors='coerce')
df['date'] = df.datetime.dt.date
df

,station,datetime,4in_vwc,4in_ec,4in_soiltemp,25in_vwc,24in_ec,24in_soiltemp,date
0,rfd01,2014-06-11 11:00:00,0.447,0.495,23.770,0.310,0.308,21.250,2014-06-11
1,rfd01,2014-06-11 12:00:00,0.449,0.502,25.960,0.309,0.309,22.530,2014-06-11
2,rfd01,2014-06-11 13:00:00,0.452,0.510,26.440,0.309,0.310,23.560,2014-06-11
3,rfd01,2014-06-11 14:00:00,0.453,0.517,26.560,0.309,0.311,23.970,2014-06-11
4,rfd01,2014-06-11 15:00:00,0.453,0.519,23.520,0.309,0.311,21.660,2014-06-11
5,rfd01,2014-06-11 16:00:00,0.449,0.518,24.980,0.309,0.311,22.410,2014-06-11
6,rfd01,2014-06-11 17:00:00,0.441,0.518,23.930,0.309,0.310,22.070,2014-06-11
7,rfd01,2014-06-11 18:00:00,0.446,0.515,21.920,0.309,0.309,20.500,2014-06-11
8,rfd01,2014-06-11 19:00:00,0.450,0.503,16.870,0.308,0.306,17.100,2014-06-11
9,rfd01,2014-06-11 20:00:00,0.448,0.496,15.220,0.308,0.305,15.480,2014-06-11
10,rfd01,2014-06-11 21:00:00,0.446,0.492,15.230,0.308,0.304,15.430,2014-06-11
11,rfd01,2014-06-11 22:00:00,0.444,0.488,14.570,0.308,0.303,14.870,2014-06-11
12,rfd01,2014-06-11 23:00:00,0.442,0.484,14.220,0.307,0.302,14.600,2014-06-11
13,rfd01,2014-06-12 00:00:00,0.441,0.480,13.750,0.307,0.301,14.390,2014-06-12
14,rfd01,2014-06-12 01:00:00,0.439,0.477,13.890,0.307,0.300,14.570,2014-06-12
15,rfd01,2014-06-12 02:00:00,0.437,0.472,13.380,0.306,0.300,14.030,2014-06-12
16,rfd01,2014-06-12 03:00:00,0.435,0.470,12.950,0.306,0.299,13.460,2014-06-12
17,rfd01,2014-06-12 04:00:00,0.434,0.467,13.610,0.306,0.298,13.950,2014-06-12
18,rfd01,2014-06-12 05:00:00,0.432,0.464,13.560,0.305,0.297,14.370,2014-06-12
19,rfd01,2014-06-12 06:00:00,0.431,0.462,14.020,0.305,0.297,14.690,2014-06-12
20,rfd01,2014-06-12 07:00:00,0.431,0.461,15.070,0.305,0.296,15.320,2014-06-12
21,rfd01,2014-06-12 08:00:00,0.430,0.460,17.180,0.304,0.296,16.370,2014-06-12
22,rfd01,2014-06-12 09:00:00,0.428,0.465,17.870,0.304,0.296,16.870,2014-06-12
23,rfd01,2014-06-12 10:00:00,0.430,0.463,20.060,0.303,0.296,18.200,2014-06-12
24,rfd01,2014-06-12 11:00:00,0.430,0.466,22.010,0.303,0.297,19.830,2014-06-12
25,rfd01,2014-06-12 12:00:00,0.432,0.472,23.400,0.302,0.298,21.460,2014-06-12
26,rfd01,2014-06-12 13:00:00,0.433,0.478,24.040,0.302,0.299,22.920,2014-06-12
27,rfd01,2014-06-12 14:00:00,0.435,0.483,24.610,0.302,0.300,23.580,2014-06-12
28,rfd01,2014-06-12 15:00:00,0.436,0.488,26.060,0.302,0.300,23.130,2014-06-12
29,rfd01,2014-06-12 16:00:00,0.437,0.495,24.470,0.301,0.300,22.290,2014-06-12
...,...,...,...,...,...,...,...,...,...
39826,rfd01,2018-12-29 19:00:00,0.287,0.174,0.869,7999.000,0.168,4.793,2018-12-29
39827,rfd01,2018-12-29 20:00:00,0.287,0.174,0.870,7999.000,0.167,4.828,2018-12-29
39828,rfd01,2018-12-29 21:00:00,0.287,0.174,0.866,7999.000,0.167,4.800,2018-12-29
39829,rfd01,2018-12-29 22:00:00,0.287,0.174,0.845,7999.000,0.167,4.772,2018-12-29
39830,rfd01,2018-12-29 23:00:00,0.287,0.174,0.808,7999.000,0.167,4.756,2018-12-29
39831,rfd01,2018-12-30 00:00:00,0.287,0.174,0.763,7999.000,0.167,4.734,2018-12-30
39832,rfd01,2018-12-30 01:00:00,0.287,0.174,0.723,7999.000,0.167,4.733,2018-12-30
39833,rfd01,2018-12-30 02:00:00,0.287,0.173,0.669,7999.000,0.167,4.732,2018-12-30
39834,rfd01,2018-12-30 03:00:00,0.286,0.173,0.620,7999.000,0.167,4.732,2018-12-30
39835,rfd01,2018-12-30 04:00:00,0.286,0.173,0.586,7999.000,0.167,4.701,2018-12-30
39836,rfd01,2018-12-30 05:00:00,0.286,0.173,0.550,7999.000,0.167,4.708,2018-12-30
39837,rfd01,2018-12-30 06:00:00,0.286,0.172,0.512,7999.000,0.167,4.682,2018-12-30
39838,rfd01,2018-12-30 07:00:00,0.286,0.172,0.479,7999.000,0.167,4.662,2018-12-30
39839,rfd01,2018-12-30 08:00:00,0.285,0.172,0.465,7999.000,0.167,4.651,2018-12-30
39840,rfd01,2018-12-30 09:00:00,0.285,0.171,0.413,7999.000,0.167,4.667,2018-12-30
39841,rfd01,2018-12-30 10:00:00,0.285,0.171,0.384,7999.000,0.167,4.649,2018-12-30
39842,rfd01,2018-12-30 11:00:00,0.285,0.171,0.354,7999.000,0.167,4.626,2018-12-30
39843,rfd01,2018-12-30 12:00:00,0.284,0.171,0.353,7999.000,0.167,4.619,2018-12-30
39844,rfd01,2018-12-30 13:00:00,0.285,0.170,0.370,7999.000,0.167,4.602,2018-12-30
39845,rfd01,2018-12-30 14:00:00,0.285,0.170,0.394,7999.000,0.167,4.599,2018-12-30
39846,rfd01,2018-12-30 15:00:00,0.285,0.170,0.420,7999.000,0.167,4.593,2018-12-30
39847,rfd01,2018-12-30 16:00:00,0.284,0.170,0.446,7999.000,0.166,4.582,2018-12-30
39848,rfd01,2018-12-30 17:00:00,0.285,0.170,0.465,7999.000,0.167,4.569,2018-12-30
39849,rfd01,2018-12-30 18:00:00,0.285,0.170,0.495,7999.000,0.166,4.562,2018-12-30
39850,rfd01,2018-12-30 19:00:00,0.284,0.171,0.518,7999.000,0.166,4.547,2018-12-30
39851,rfd01,2018-12-30 20:00:00,0.285,0.171,0.539,7999.000,0.166,4.528,2018-12-30
39852,rfd01,2018-12-30 21:00:00,0.285,0.171,0.567,7999.000,0.166,4.534,2018-12-30
39853,rfd01,2018-12-30 22:00:00,0.285,0.171,0.572,7999.000,0.166,4.519,2018-12-30
39854,rfd01,2018-12-30 23:00:00,0.285,0.171,0.571,7999.000,0.166,4.485,2018-12-30
39855,rfd01,2018-12-31 00:00:00,0.285,0.171,0.603,7999.000,0.166,4.478,2018-12-31