In [28]:
import os
import urllib
import pandas as pd
import numpy as np

In [29]:
path = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\minimums\COOP_minimums'
os.chdir(path)
xl_file = r"C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\colocation_metadata.xlsx"
csv = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\normals\COOP_Normals\csv.csv'

xl = pd.ExcelFile(xl_file)

meta = xl.parse('metadata')
meta['sdate'] = meta.sdate.dt.date
meta['edate'] = meta.edate.dt.date
meta.drop(meta.columns[3],axis=1)

       ID       sdate       edate  COOP_ID
0   AKR02  1992-07-01  2019-08-26    50109
1   ALT01  1992-03-17  2019-08-26    53006
2   AVN01  1992-06-04  2019-08-26    50839
3   BNV01  2010-10-12  2019-08-26    51071
4   BRG01  2002-07-31  2019-08-26    50945
..    ...         ...         ...      ...
67  WLS01  2012-04-11  2019-08-26    58793
68  WRY02  2015-04-01  2019-08-26    59243
69  YJK01  1992-01-02  2019-08-26    59275
70  YUC01  2002-08-23  2019-08-26    51886
71  YUM02  1996-05-08  2019-08-26    59295

[72 rows x 4 columns]

In [30]:
n = 0
for index,rows in meta.iterrows():
    print('Grabbing COOP data for ' + str(meta.ID[n]))
    urllib.request.urlretrieve(
        'http://data.rcc-acis.org/StnData?sid=0' + str(meta.COOP_ID[n]) + '&sdate='+ str(meta.sdate[n]) + '&edate=' + str(meta.edate[n]) + '&elems=maxt,mint,avgt,pcpn&output=csv',
        filename=csv)
    print('Cleaning COOP data for ' + str(meta.ID[n]))
    df = pd.read_csv(csv)
    df = df.reset_index()
    df.columns.values[0] = 'date'
    df.columns.values[1] = 'maxt'
    df.columns.values[2] = 'mint'
    df.columns.values[3] = 'avgt'
    df.columns.values[4] = 'pcpn'
    df['date'] = pd.to_datetime(df.date)
    df['julian'] = df.date.dt.strftime('%j')
    df = df.replace('M', np.nan, regex=True)
    df = df.replace('T', 0.005, regex=True)
    df.maxt = df.maxt.astype(float)
    df.mint = df.mint.astype(float)
    df.avgt = df.avgt.astype(float)
    df.pcpn = df.pcpn.astype(float)
    print('Analyzing COOP data for ' + str(meta.ID[n]))
    normals = df.groupby(['julian']).min().reset_index()
    normals.to_csv(path + r'/' + str(meta.ID[n]) + '_COOPmin.csv')
    n = n+1

Grabbing COOP data for AKR02
Cleaning COOP data for AKR02
Analyzing COOP data for AKR02
Grabbing COOP data for ALT01
Cleaning COOP data for ALT01
Analyzing COOP data for ALT01
Grabbing COOP data for AVN01
Cleaning COOP data for AVN01
Analyzing COOP data for AVN01
Grabbing COOP data for BNV01
Cleaning COOP data for BNV01
Analyzing COOP data for BNV01
Grabbing COOP data for BRG01
Cleaning COOP data for BRG01
Analyzing COOP data for BRG01
Grabbing COOP data for BRK01
Cleaning COOP data for BRK01
Analyzing COOP data for BRK01
Grabbing COOP data for BRL02
Cleaning COOP data for BRL02
Analyzing COOP data for BRL02
Grabbing COOP data for BRL03
Cleaning COOP data for BRL03
Analyzing COOP data for BRL03
Grabbing COOP data for CBL01
Cleaning COOP data for CBL01
Analyzing COOP data for CBL01
Grabbing COOP data for CKP01
Cleaning COOP data for CKP01
Analyzing COOP data for CKP01
Grabbing COOP data for CNN01
Cleaning COOP data for CNN01
Analyzing COOP data for CNN01
Grabbing COOP data for COW01
Cleaning COOP data for COW01
Analyzing COOP data for COW01
Grabbing COOP data for CTR01
Cleaning COOP data for CTR01
Analyzing COOP data for CTR01
Grabbing COOP data for CTR02
Cleaning COOP data for CTR02
Analyzing COOP data for CTR02
Grabbing COOP data for CTZ01
Cleaning COOP data for CTZ01
Analyzing COOP data for CTZ01
Grabbing COOP data for DLT01
Cleaning COOP data for DLT01
Analyzing COOP data for DLT01
Grabbing COOP data for DVC01
Cleaning COOP data for DVC01
Analyzing COOP data for DVC01
Grabbing COOP data for EAC01
Cleaning COOP data for EAC01
Analyzing COOP data for EAC01
Grabbing COOP data for EKT01
Cleaning COOP data for EKT01
Analyzing COOP data for EKT01
Grabbing COOP data for FRT02
Cleaning COOP data for FRT02
Analyzing COOP data for FRT02
Grabbing COOP data for FTC01
Cleaning COOP data for FTC01
Analyzing COOP data for FTC01
Grabbing COOP data for FTC03
Cleaning COOP data for FTC03
Analyzing COOP data for FTC03
Grabbing COOP data for FTL01
Cleaning COOP data for FTL01
Analyzing COOP data for FTL01
Grabbing COOP data for FWL01
Cleaning COOP data for FWL01
Analyzing COOP data for FWL01
Grabbing COOP data for GLY04
Cleaning COOP data for GLY04
Analyzing COOP data for GLY04
Grabbing COOP data for GUN01
Cleaning COOP data for GUN01
Analyzing COOP data for GUN01
Grabbing COOP data for HEB01
Cleaning COOP data for HEB01
Analyzing COOP data for HEB01
Grabbing COOP data for HLY01
Cleaning COOP data for HLY01
Analyzing COOP data for HLY01
Grabbing COOP data for HLY02
Cleaning COOP data for HLY02
Analyzing COOP data for HLY02
Grabbing COOP data for HNE01
Cleaning COOP data for HNE01
Analyzing COOP data for HNE01
Grabbing COOP data for HOT01
Cleaning COOP data for HOT01
Analyzing COOP data for HOT01
Grabbing COOP data for HXT01
Cleaning COOP data for HXT01
Analyzing COOP data for HXT01
Grabbing COOP data for HYD01
Cleaning COOP data for HYD01
Analyzing COOP data for HYD01
Grabbing COOP data for HYK02
Cleaning COOP data for HYK02
Analyzing COOP data for HYK02
Grabbing COOP data for IDL01
Cleaning COOP data for IDL01
Analyzing COOP data for IDL01
Grabbing COOP data for ILF01
Cleaning COOP data for ILF01
Analyzing COOP data for ILF01
Grabbing COOP data for JFN01
Cleaning COOP data for JFN01
Analyzing COOP data for JFN01
Grabbing COOP data for KRK01
Cleaning COOP data for KRK01
Analyzing COOP data for KRK01
Grabbing COOP data for KSY01
Cleaning COOP data for KSY01
Analyzing COOP data for KSY01
Grabbing COOP data for KSY02
Cleaning COOP data for KSY02
Analyzing COOP data for KSY02
Grabbing COOP data for LAM01
Cleaning COOP data for LAM01
Analyzing COOP data for LAM01
Grabbing COOP data for LAM03
Cleaning COOP data for LAM03
Analyzing COOP data for LAM03
Grabbing COOP data for LAM04
Cleaning COOP data for LAM04
Analyzing COOP data for LAM04
Grabbing COOP data for LAR01
Cleaning COOP data for LAR01
Analyzing COOP data for LAR01
Grabbing COOP data for LCN01
Cleaning COOP data for LCN01
Analyzing COOP data for LCN01
Grabbing COOP data for LJR01
Cleaning COOP data for LJR01
Analyzing COOP data for LJR01
Grabbing COOP data for LJT01
Cleaning COOP data for LJT01
Analyzing COOP data for LJT01
Grabbing COOP data for LSL01
Cleaning COOP data for LSL01
Analyzing COOP data for LSL01
Grabbing COOP data for MCL01
Cleaning COOP data for MCL01
Analyzing COOP data for MCL01
Grabbing COOP data for MNC01
Cleaning COOP data for MNC01
Analyzing COOP data for MNC01
Grabbing COOP data for MTR01
Cleaning COOP data for MTR01
Analyzing COOP data for MTR01
Grabbing COOP data for ORM01
Cleaning COOP data for ORM01
Analyzing COOP data for ORM01
Grabbing COOP data for OTH01
Cleaning COOP data for OTH01
Analyzing COOP data for OTH01
Grabbing COOP data for PAI01
Cleaning COOP data for PAI01
Analyzing COOP data for PAI01
Grabbing COOP data for PKH01
Cleaning COOP data for PKH01
Analyzing COOP data for PKH01
Grabbing COOP data for PKR01
Cleaning COOP data for PKR01
Analyzing COOP data for PKR01
Grabbing COOP data for PNR01
Cleaning COOP data for PNR01
Analyzing COOP data for PNR01
Grabbing COOP data for RFD01
Cleaning COOP data for RFD01
Analyzing COOP data for RFD01
Grabbing COOP data for SAN01
Cleaning COOP data for SAN01
Analyzing COOP data for SAN01
Grabbing COOP data for SBT01
Cleaning COOP data for SBT01
Analyzing COOP data for SBT01
Grabbing COOP data for SCM01
Cleaning COOP data for SCM01
Analyzing COOP data for SCM01
Grabbing COOP data for SLD01
Cleaning COOP data for SLD01
Analyzing COOP data for SLD01
Grabbing COOP data for SLT01
Cleaning COOP data for SLT01
Analyzing COOP data for SLT01
Grabbing COOP data for STG01
Cleaning COOP data for STG01
Analyzing COOP data for STG01
Grabbing COOP data for STN01
Cleaning COOP data for STN01
Analyzing COOP data for STN01
Grabbing COOP data for WCF01
Cleaning COOP data for WCF01
Analyzing COOP data for WCF01
Grabbing COOP data for WFD01
Cleaning COOP data for WFD01
Analyzing COOP data for WFD01
Grabbing COOP data for WLS01
Cleaning COOP data for WLS01
Analyzing COOP data for WLS01
Grabbing COOP data for WRY02
Cleaning COOP data for WRY02
Analyzing COOP data for WRY02
Grabbing COOP data for YJK01
Cleaning COOP data for YJK01
Analyzing COOP data for YJK01
Grabbing COOP data for YUC01
Cleaning COOP data for YUC01
Analyzing COOP data for YUC01
Grabbing COOP data for YUM02
Cleaning COOP data for YUM02
Analyzing COOP data for YUM02

In [144]:
df = df.replace('M', np.nan, regex=True)
df = df.replace('T', 0.005, regex=True)
df.maxt = df.maxt.astype(float)
df.mint = df.mint.astype(float)
df.avgt = df.avgt.astype(float)
df.pcpn = df.pcpn.astype(float)

normals = df.groupby(['julian']).mean().reset_index()

In [145]:
normals.to_csv(path + r'/' + str(df.ID[n]) + '_COOPmax.csv'