In [25]:
# Loads the libraries required to build the environment we will be using in this tutorial
import os
import urllib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from scipy import stats
import calendar

In [26]:
path = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\normals'
os.chdir(path)

xlsx = r"C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\metadata.xlsx"

xsls_file = pd.ExcelFile(xlsx)
xsls_file.sheet_names

['metadata']

In [27]:
df= xsls_file.parse('metadata')
df

       ID      sdate      edate
0   AKR02 1992-07-01 2019-08-26
1   ALT01 1992-03-17 2019-08-26
2   AVN01 1992-06-04 2019-08-26
3   BNV01 2010-10-12 2019-08-26
4   BRG01 2002-07-31 2019-08-26
..    ...        ...        ...
80  WLS01 2012-04-11 2019-08-26
81  WRY02 2015-04-01 2019-08-26
82  YJK01 1992-01-02 2019-08-26
83  YUC01 2002-08-23 2019-08-26
84  YUM02 1996-05-08 2019-08-26

[85 rows x 3 columns]

In [28]:
df['sdate'] = pd.to_datetime(df.sdate)

In [29]:
df['sdate'] = df.sdate.dt.date

In [30]:
df['edate'] = df.edate.dt.date

In [31]:
n=0
for index,rows in df.iterrows():
    print(str(df['ID'][n]) + 'began collecting data on ' + str(df['sdate'][n]))
    n = n+1

AKR02began collecting data on 1992-07-01
ALT01began collecting data on 1992-03-17
AVN01began collecting data on 1992-06-04
BNV01began collecting data on 2010-10-12
BRG01began collecting data on 2002-07-31
BRK01began collecting data on 2013-11-07
BRL02began collecting data on 1992-01-02
BRL03began collecting data on 2008-03-21
CBL01began collecting data on 2015-05-08
CBN01began collecting data on 2018-03-30
CCR01began collecting data on 2019-07-25
CKP01began collecting data on 2014-07-25
CLK01began collecting data on 2018-04-25
CNN01began collecting data on 2010-12-31
COW01began collecting data on 2009-06-10
CTR01began collecting data on 1993-10-08
CTR02began collecting data on 2003-10-02
CTZ01began collecting data on 1992-01-02
DLT01began collecting data on 1995-04-19
DRG01began collecting data on 2018-05-30
DVC01began collecting data on 1992-10-28
EAC01began collecting data on 2000-07-17
EKT01began collecting data on 2015-05-07
FRT02began collecting data on 1992-06-16
FTC01began collecting data on 1992-02-01
FTC03began collecting data on 1992-05-08
FTL01began collecting data on 1992-03-17
FWL01began collecting data on 2005-03-17
GBY01began collecting data on 2018-04-23
GLY04began collecting data on 2008-06-05
GUN01began collecting data on 2015-02-25
GYP01began collecting data on 2017-10-11
HEB01began collecting data on 2009-06-10
HLY01began collecting data on 2001-09-27
HLY02began collecting data on 2005-05-21
HNE01began collecting data on 2000-02-14
HOT01began collecting data on 1998-05-21
HXT01began collecting data on 1997-03-27
HYD01began collecting data on 2011-11-16
HYK02began collecting data on 1992-01-02
IDL01began collecting data on 1992-01-02
IGN01began collecting data on 2018-04-20
ILF01began collecting data on 2008-02-02
JFN01began collecting data on 2012-01-01
KLN01began collecting data on 2018-04-12
KRK01began collecting data on 1996-05-13
KRM01began collecting data on 2018-04-30
KSY01began collecting data on 1992-05-01
KSY02began collecting data on 2015-01-01
LAM01began collecting data on 1996-08-03
LAM03began collecting data on 2002-07-31
LAM04began collecting data on 2005-05-11
LAR01began collecting data on 2009-06-10
LCN01began collecting data on 1992-03-04
LJR01began collecting data on 2005-05-19
LJT01began collecting data on 2005-03-17
LSL01began collecting data on 2012-02-10
MCL01began collecting data on 2005-03-17
MKR01began collecting data on 2018-04-26
MNC01began collecting data on 2010-10-29
MTR01began collecting data on 2015-02-24
NWD01began collecting data on 2018-06-14
ORM01began collecting data on 2006-01-02
OTH01began collecting data on 1992-07-28
PAI01began collecting data on 2001-09-26
PGS01began collecting data on 2018-04-20
PKH01began collecting data on 1992-03-17
PKR01began collecting data on 2015-03-12
PNR01began collecting data on 2010-10-13
RFD01began collecting data on 1992-06-04
SAN01began collecting data on 2000-08-12
SBT01began collecting data on 2015-04-02
SCM01began collecting data on 2008-07-24
SLD01began collecting data on 2010-07-28
SLT01began collecting data on 2015-05-08
STG01began collecting data on 2006-03-24
STN01began collecting data on 2006-04-02
TWC01began collecting data on 1998-06-30
WCF01began collecting data on 2010-09-20
WFD01began collecting data on 2004-11-30
WLS01began collecting data on 2012-04-11
WRY02began collecting data on 2015-04-01
YJK01began collecting data on 1992-01-02
YUC01began collecting data on 2002-08-23
YUM02began collecting data on 1996-05-08

ValueError: not enough values to unpack (expected 3, got 2)