In [1]:
import os
import pandas as pd
import numpy as np
import urllib
from datetime import datetime,timedelta

In [5]:
path = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\missing_data'
os.chdir(path)

today = datetime.now().strftime("%Y-%m-%d")
yesterday = datetime.strftime(datetime.now() - timedelta(1), "%Y-%m-%d")

csv = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\missing_data\csv.csv'
f = open(csv,'w+')

fm_txt = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\missing_data\five_minute\missing_data_report_' + str(yesterday) + '.txt'
hr_txt = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\missing_data\hourly\missing_data_report_' + str(yesterday) + '.txt'
dy_txt = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\missing_data\daily\missing_data_report_' + str(yesterday) + '.txt'

g = open(fm_txt,'a')
h = open(hr_txt,'a')
i = open(dy_txt,'a')

xl_file = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\meta_files\colocation_metadata.xlsx'

In [17]:
urllib.request.urlretrieve('http://coagmet.colostate.edu/cgi-bin/web_services.pl?type=five_minute&sids=hly02&sdate=' + str(yesterday) + '&edate=' + str(today) + '&elems=tmean,rh,vp,sr,ws,wind_vec,pp,st5,st15,gust,gusttm,gustdir',filename=csv)
df = pd.read_csv(csv,error_bad_lines=False)
df = df.reset_index()
df.columns = ['station','date','tmean','rh','vp','sr','ws','wind_vec','pp','st5','st15','gust','gusttm','gustdir']
df.drop(df.tail(1).index,inplace=True)
df

,station,date,tmean,rh,vp,sr,ws,wind_vec,pp,st5,st15,gust,gusttm,gustdir
0,hly02,2019-10-02 00:00:00,9.84,0.978,1.187,0.016,6.310,50.920,0.0,NaN,NaN,8.080,23:56:00,53.750
1,hly02,2019-10-02 00:05:00,9.79,0.977,1.182,0.017,6.060,49.230,0.0,NaN,NaN,7.400,00:03:00,50.330
2,hly02,2019-10-02 00:10:00,9.70,0.976,1.174,0.027,6.232,44.270,0.0,NaN,NaN,9.120,00:06:00,40.460
3,hly02,2019-10-02 00:15:00,9.74,0.977,1.178,0.009,4.450,36.150,0.0,NaN,NaN,5.975,00:11:00,48.760
4,hly02,2019-10-02 00:20:00,9.68,0.975,1.171,0.011,5.425,40.880,0.0,NaN,NaN,7.850,00:19:00,37.790
5,hly02,2019-10-02 00:25:00,9.69,0.974,1.170,0.005,5.362,36.230,0.0,NaN,NaN,7.250,00:23:00,36.630
6,hly02,2019-10-02 00:30:00,9.70,0.971,1.168,0.012,5.723,41.160,0.0,NaN,NaN,8.080,00:28:00,37.530
7,hly02,2019-10-02 00:35:00,9.69,0.969,1.165,0.005,5.787,46.490,0.0,NaN,NaN,7.400,00:31:00,59.210
8,hly02,2019-10-02 00:40:00,9.68,0.965,1.159,0.008,5.280,41.880,0.0,NaN,NaN,7.025,00:40:00,44.780
9,hly02,2019-10-02 00:45:00,9.63,0.962,1.151,0.011,5.213,42.980,0.0,NaN,NaN,7.250,00:40:00,38.880
10,hly02,2019-10-02 00:50:00,9.57,0.960,1.144,0.007,6.000,40.540,0.0,NaN,NaN,8.530,00:47:00,34.320
11,hly02,2019-10-02 00:55:00,9.55,0.960,1.143,0.012,4.982,36.680,0.0,NaN,NaN,6.650,00:54:00,20.230
12,hly02,2019-10-02 01:00:00,9.54,0.961,1.144,0.012,3.623,22.150,0.0,NaN,NaN,5.150,00:56:00,36.700
13,hly02,2019-10-02 01:05:00,9.47,0.957,1.133,0.017,3.598,3.909,0.0,NaN,NaN,4.850,01:02:00,3.008
14,hly02,2019-10-02 01:10:00,9.32,0.954,1.118,0.005,5.137,27.640,0.0,NaN,NaN,6.575,01:08:00,27.940
15,hly02,2019-10-02 01:15:00,9.19,0.955,1.110,0.022,5.370,36.420,0.0,NaN,NaN,7.250,01:13:00,25.370
16,hly02,2019-10-02 01:20:00,9.01,0.963,1.106,0.035,5.738,44.140,0.0,NaN,NaN,7.550,01:15:00,39.980
17,hly02,2019-10-02 01:25:00,8.90,0.971,1.107,0.039,5.430,53.640,0.0,NaN,NaN,6.875,01:23:00,63.480
18,hly02,2019-10-02 01:30:00,8.83,0.975,1.106,0.038,5.270,47.430,0.0,NaN,NaN,7.775,01:26:00,38.330
19,hly02,2019-10-02 01:35:00,8.74,0.977,1.102,0.040,5.398,39.330,0.0,NaN,NaN,6.725,01:33:00,29.060
20,hly02,2019-10-02 01:40:00,8.68,0.979,1.099,0.039,5.453,40.990,0.0,NaN,NaN,8.000,01:39:00,34.830
21,hly02,2019-10-02 01:45:00,8.66,0.981,1.099,0.040,5.215,35.530,0.0,NaN,NaN,7.100,01:42:00,46.140
22,hly02,2019-10-02 01:50:00,8.66,0.983,1.102,0.039,5.045,32.140,0.0,NaN,NaN,7.250,01:46:00,42.130
23,hly02,2019-10-02 01:55:00,8.63,0.984,1.101,0.039,5.088,47.160,0.0,NaN,NaN,8.600,01:54:00,53.410
24,hly02,2019-10-02 02:00:00,8.54,0.983,1.093,0.038,5.597,51.020,0.0,NaN,NaN,6.875,01:56:00,57.130
25,hly02,2019-10-02 02:05:00,8.51,0.983,1.091,0.040,5.453,54.940,0.0,NaN,NaN,8.080,02:02:00,72.330
26,hly02,2019-10-02 02:10:00,8.53,0.983,1.093,0.039,4.768,45.050,0.0,NaN,NaN,7.100,02:09:00,41.040
27,hly02,2019-10-02 02:15:00,8.51,0.982,1.090,0.035,5.098,33.830,0.0,NaN,NaN,7.325,02:11:00,38.690
28,hly02,2019-10-02 02:20:00,8.52,0.981,1.089,0.036,3.990,25.440,0.0,NaN,NaN,6.050,02:15:00,26.630
29,hly02,2019-10-02 02:25:00,8.58,0.981,1.095,0.039,3.465,13.610,0.0,NaN,NaN,4.700,02:24:00,29.570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,hly02,2019-10-02 21:35:00,10.32,0.953,1.196,-0.001,3.403,59.210,0.0,NaN,NaN,4.775,21:34:00,52.870
260,hly02,2019-10-02 21:40:00,10.42,0.937,1.183,0.005,3.090,58.460,0.0,NaN,NaN,4.100,21:39:00,56.970
261,hly02,2019-10-02 21:45:00,10.31,0.931,1.166,0.012,3.938,53.440,0.0,NaN,NaN,5.675,21:43:00,64.680
262,hly02,2019-10-02 21:50:00,10.24,0.927,1.156,0.008,3.938,57.270,0.0,NaN,NaN,5.150,21:46:00,56.260
263,hly02,2019-10-02 21:55:00,10.19,0.925,1.149,0.008,3.822,54.210,0.0,NaN,NaN,4.850,21:54:00,63.270
264,hly02,2019-10-02 22:00:00,10.16,0.923,1.145,0.008,3.297,50.630,0.0,NaN,NaN,5.075,22:00:00,60.500
265,hly02,2019-10-02 22:05:00,10.10,0.917,1.133,0.005,4.697,55.160,0.0,NaN,NaN,6.275,22:03:00,84.700
266,hly02,2019-10-02 22:10:00,10.06,0.908,1.119,0.003,5.120,50.860,0.0,NaN,NaN,6.725,22:08:00,43.420
267,hly02,2019-10-02 22:15:00,10.04,0.907,1.115,0.005,3.990,55.020,0.0,NaN,NaN,5.825,22:12:00,59.110
268,hly02,2019-10-02 22:20:00,9.98,0.907,1.111,0.009,3.798,59.150,0.0,NaN,NaN,4.850,22:16:00,45.410
269,hly02,2019-10-02 22:25:00,9.94,0.902,1.102,0.011,3.930,58.880,0.0,NaN,NaN,5.600,22:22:00,49.610
270,hly02,2019-10-02 22:30:00,9.89,0.900,1.096,0.008,4.275,58.480,0.0,NaN,NaN,5.525,22:26:00,59.890
271,hly02,2019-10-02 22:35:00,9.85,0.897,1.090,0.019,4.727,52.840,0.0,NaN,NaN,6.275,22:34:00,67.260
272,hly02,2019-10-02 22:40:00,9.84,0.894,1.085,0.009,4.408,53.280,0.0,NaN,NaN,5.675,22:37:00,44.710
273,hly02,2019-10-02 22:45:00,9.80,0.896,1.085,0.005,3.985,46.900,0.0,NaN,NaN,5.600,22:44:00,50.330
274,hly02,2019-10-02 22:50:00,9.78,0.888,1.074,0.007,5.233,52.190,0.0,NaN,NaN,7.700,22:46:00,73.890
275,hly02,2019-10-02 22:55:00,9.76,0.883,1.066,0.009,5.775,44.670,0.0,NaN,NaN,8.150,22:54:00,47.690
276,hly02,2019-10-02 23:00:00,9.75,0.884,1.066,0.009,5.595,44.280,0.0,NaN,NaN,7.175,22:58:00,44.730
277,hly02,2019-10-02 23:05:00,9.74,0.881,1.062,0.011,5.945,50.630,0.0,NaN,NaN,8.220,23:03:00,56.830
278,hly02,2019-10-02 23:10:00,9.72,0.879,1.059,0.004,5.445,47.920,0.0,NaN,NaN,7.550,23:08:00,45.990
279,hly02,2019-10-02 23:15:00,9.64,0.879,1.053,0.001,5.197,43.620,0.0,NaN,NaN,7.175,23:12:00,53.460
280,hly02,2019-10-02 23:20:00,9.40,0.884,1.041,0.017,4.000,37.920,0.0,NaN,NaN,5.375,23:15:00,41.020
281,hly02,2019-10-02 23:25:00,9.18,0.894,1.037,0.016,3.595,51.140,0.0,NaN,NaN,5.000,23:22:00,56.350
282,hly02,2019-10-02 23:30:00,9.01,0.897,1.030,0.016,2.780,56.690,0.0,NaN,NaN,3.875,23:28:00,47.450
283,hly02,2019-10-02 23:35:00,8.87,0.895,1.018,0.009,3.220,55.990,0.0,NaN,NaN,4.100,23:32:00,56.880
284,hly02,2019-10-02 23:40:00,8.79,0.898,1.015,0.011,2.585,45.890,0.0,NaN,NaN,3.275,23:36:00,56.570
285,hly02,2019-10-02 23:45:00,8.76,0.902,1.018,0.011,2.250,44.000,0.0,NaN,NaN,3.500,23:40:00,40.390
286,hly02,2019-10-02 23:50:00,8.87,0.900,1.023,0.009,2.480,42.410,0.0,NaN,NaN,3.800,23:46:00,36.120
287,hly02,2019-10-02 23:55:00,8.95,0.894,1.022,0.007,2.690,49.880,0.0,NaN,NaN,3.800,23:52:00,62.780
288,hly02,2019-10-03 00:00:00,8.95,0.891,1.018,0.003,2.405,43.910,0.0,NaN,NaN,3.950,23:58:00,38.500

In [18]:
df['date'] = pd.to_datetime(df.date)
r = pd.date_range(start=yesterday,end=today,freq='5min')
df = df.set_index('date').reindex(r,copy=False).rename_axis('date')
df

,station,tmean,rh,vp,sr,ws,wind_vec,pp,st5,st15,gust,gusttm,gustdir
date,,,,,,,,,,,,,
2019-10-02 00:00:00,hly02,9.84,0.978,1.187,0.016,6.310,50.920,0.0,NaN,NaN,8.080,23:56:00,53.750
2019-10-02 00:05:00,hly02,9.79,0.977,1.182,0.017,6.060,49.230,0.0,NaN,NaN,7.400,00:03:00,50.330
2019-10-02 00:10:00,hly02,9.70,0.976,1.174,0.027,6.232,44.270,0.0,NaN,NaN,9.120,00:06:00,40.460
2019-10-02 00:15:00,hly02,9.74,0.977,1.178,0.009,4.450,36.150,0.0,NaN,NaN,5.975,00:11:00,48.760
2019-10-02 00:20:00,hly02,9.68,0.975,1.171,0.011,5.425,40.880,0.0,NaN,NaN,7.850,00:19:00,37.790
2019-10-02 00:25:00,hly02,9.69,0.974,1.170,0.005,5.362,36.230,0.0,NaN,NaN,7.250,00:23:00,36.630
2019-10-02 00:30:00,hly02,9.70,0.971,1.168,0.012,5.723,41.160,0.0,NaN,NaN,8.080,00:28:00,37.530
2019-10-02 00:35:00,hly02,9.69,0.969,1.165,0.005,5.787,46.490,0.0,NaN,NaN,7.400,00:31:00,59.210
2019-10-02 00:40:00,hly02,9.68,0.965,1.159,0.008,5.280,41.880,0.0,NaN,NaN,7.025,00:40:00,44.780
2019-10-02 00:45:00,hly02,9.63,0.962,1.151,0.011,5.213,42.980,0.0,NaN,NaN,7.250,00:40:00,38.880
2019-10-02 00:50:00,hly02,9.57,0.960,1.144,0.007,6.000,40.540,0.0,NaN,NaN,8.530,00:47:00,34.320
2019-10-02 00:55:00,hly02,9.55,0.960,1.143,0.012,4.982,36.680,0.0,NaN,NaN,6.650,00:54:00,20.230
2019-10-02 01:00:00,hly02,9.54,0.961,1.144,0.012,3.623,22.150,0.0,NaN,NaN,5.150,00:56:00,36.700
2019-10-02 01:05:00,hly02,9.47,0.957,1.133,0.017,3.598,3.909,0.0,NaN,NaN,4.850,01:02:00,3.008
2019-10-02 01:10:00,hly02,9.32,0.954,1.118,0.005,5.137,27.640,0.0,NaN,NaN,6.575,01:08:00,27.940
2019-10-02 01:15:00,hly02,9.19,0.955,1.110,0.022,5.370,36.420,0.0,NaN,NaN,7.250,01:13:00,25.370
2019-10-02 01:20:00,hly02,9.01,0.963,1.106,0.035,5.738,44.140,0.0,NaN,NaN,7.550,01:15:00,39.980
2019-10-02 01:25:00,hly02,8.90,0.971,1.107,0.039,5.430,53.640,0.0,NaN,NaN,6.875,01:23:00,63.480
2019-10-02 01:30:00,hly02,8.83,0.975,1.106,0.038,5.270,47.430,0.0,NaN,NaN,7.775,01:26:00,38.330
2019-10-02 01:35:00,hly02,8.74,0.977,1.102,0.040,5.398,39.330,0.0,NaN,NaN,6.725,01:33:00,29.060
2019-10-02 01:40:00,hly02,8.68,0.979,1.099,0.039,5.453,40.990,0.0,NaN,NaN,8.000,01:39:00,34.830
2019-10-02 01:45:00,hly02,8.66,0.981,1.099,0.040,5.215,35.530,0.0,NaN,NaN,7.100,01:42:00,46.140
2019-10-02 01:50:00,hly02,8.66,0.983,1.102,0.039,5.045,32.140,0.0,NaN,NaN,7.250,01:46:00,42.130
2019-10-02 01:55:00,hly02,8.63,0.984,1.101,0.039,5.088,47.160,0.0,NaN,NaN,8.600,01:54:00,53.410
2019-10-02 02:00:00,hly02,8.54,0.983,1.093,0.038,5.597,51.020,0.0,NaN,NaN,6.875,01:56:00,57.130
2019-10-02 02:05:00,hly02,8.51,0.983,1.091,0.040,5.453,54.940,0.0,NaN,NaN,8.080,02:02:00,72.330
2019-10-02 02:10:00,hly02,8.53,0.983,1.093,0.039,4.768,45.050,0.0,NaN,NaN,7.100,02:09:00,41.040
2019-10-02 02:15:00,hly02,8.51,0.982,1.090,0.035,5.098,33.830,0.0,NaN,NaN,7.325,02:11:00,38.690
2019-10-02 02:20:00,hly02,8.52,0.981,1.089,0.036,3.990,25.440,0.0,NaN,NaN,6.050,02:15:00,26.630
2019-10-02 02:25:00,hly02,8.58,0.981,1.095,0.039,3.465,13.610,0.0,NaN,NaN,4.700,02:24:00,29.570
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-10-02 21:35:00,hly02,10.32,0.953,1.196,-0.001,3.403,59.210,0.0,NaN,NaN,4.775,21:34:00,52.870
2019-10-02 21:40:00,hly02,10.42,0.937,1.183,0.005,3.090,58.460,0.0,NaN,NaN,4.100,21:39:00,56.970
2019-10-02 21:45:00,hly02,10.31,0.931,1.166,0.012,3.938,53.440,0.0,NaN,NaN,5.675,21:43:00,64.680
2019-10-02 21:50:00,hly02,10.24,0.927,1.156,0.008,3.938,57.270,0.0,NaN,NaN,5.150,21:46:00,56.260
2019-10-02 21:55:00,hly02,10.19,0.925,1.149,0.008,3.822,54.210,0.0,NaN,NaN,4.850,21:54:00,63.270
2019-10-02 22:00:00,hly02,10.16,0.923,1.145,0.008,3.297,50.630,0.0,NaN,NaN,5.075,22:00:00,60.500
2019-10-02 22:05:00,hly02,10.10,0.917,1.133,0.005,4.697,55.160,0.0,NaN,NaN,6.275,22:03:00,84.700
2019-10-02 22:10:00,hly02,10.06,0.908,1.119,0.003,5.120,50.860,0.0,NaN,NaN,6.725,22:08:00,43.420
2019-10-02 22:15:00,hly02,10.04,0.907,1.115,0.005,3.990,55.020,0.0,NaN,NaN,5.825,22:12:00,59.110
2019-10-02 22:20:00,hly02,9.98,0.907,1.111,0.009,3.798,59.150,0.0,NaN,NaN,4.850,22:16:00,45.410
2019-10-02 22:25:00,hly02,9.94,0.902,1.102,0.011,3.930,58.880,0.0,NaN,NaN,5.600,22:22:00,49.610
2019-10-02 22:30:00,hly02,9.89,0.900,1.096,0.008,4.275,58.480,0.0,NaN,NaN,5.525,22:26:00,59.890
2019-10-02 22:35:00,hly02,9.85,0.897,1.090,0.019,4.727,52.840,0.0,NaN,NaN,6.275,22:34:00,67.260
2019-10-02 22:40:00,hly02,9.84,0.894,1.085,0.009,4.408,53.280,0.0,NaN,NaN,5.675,22:37:00,44.710
2019-10-02 22:45:00,hly02,9.80,0.896,1.085,0.005,3.985,46.900,0.0,NaN,NaN,5.600,22:44:00,50.330
2019-10-02 22:50:00,hly02,9.78,0.888,1.074,0.007,5.233,52.190,0.0,NaN,NaN,7.700,22:46:00,73.890
2019-10-02 22:55:00,hly02,9.76,0.883,1.066,0.009,5.775,44.670,0.0,NaN,NaN,8.150,22:54:00,47.690
2019-10-02 23:00:00,hly02,9.75,0.884,1.066,0.009,5.595,44.280,0.0,NaN,NaN,7.175,22:58:00,44.730
2019-10-02 23:05:00,hly02,9.74,0.881,1.062,0.011,5.945,50.630,0.0,NaN,NaN,8.220,23:03:00,56.830
2019-10-02 23:10:00,hly02,9.72,0.879,1.059,0.004,5.445,47.920,0.0,NaN,NaN,7.550,23:08:00,45.990
2019-10-02 23:15:00,hly02,9.64,0.879,1.053,0.001,5.197,43.620,0.0,NaN,NaN,7.175,23:12:00,53.460
2019-10-02 23:20:00,hly02,9.40,0.884,1.041,0.017,4.000,37.920,0.0,NaN,NaN,5.375,23:15:00,41.020
2019-10-02 23:25:00,hly02,9.18,0.894,1.037,0.016,3.595,51.140,0.0,NaN,NaN,5.000,23:22:00,56.350
2019-10-02 23:30:00,hly02,9.01,0.897,1.030,0.016,2.780,56.690,0.0,NaN,NaN,3.875,23:28:00,47.450
2019-10-02 23:35:00,hly02,8.87,0.895,1.018,0.009,3.220,55.990,0.0,NaN,NaN,4.100,23:32:00,56.880
2019-10-02 23:40:00,hly02,8.79,0.898,1.015,0.011,2.585,45.890,0.0,NaN,NaN,3.275,23:36:00,56.570
2019-10-02 23:45:00,hly02,8.76,0.902,1.018,0.011,2.250,44.000,0.0,NaN,NaN,3.500,23:40:00,40.390
2019-10-02 23:50:00,hly02,8.87,0.900,1.023,0.009,2.480,42.410,0.0,NaN,NaN,3.800,23:46:00,36.120
2019-10-02 23:55:00,hly02,8.95,0.894,1.022,0.007,2.690,49.880,0.0,NaN,NaN,3.800,23:52:00,62.780
2019-10-03 00:00:00,hly02,8.95,0.891,1.018,0.003,2.405,43.910,0.0,NaN,NaN,3.950,23:58:00,38.500

In [35]:
d = 0
for index, row in df.iterrows():
    if(pd.isnull(df['tmean'][d])):
        tmean_string = (str(df.station[d]) + ' reported missing 5-minute temperature data at ' + str(df.index[d]) + '\n')
        g.write(tmean_string)
    elif(pd.isnull(df['rh'][d])):
        rh_string = (str(df.station[d]) + ' reported missing 5-minute relative humidity data at ' + str(df.index[d]) + '\n')
        g.write(rh_string)
    elif(pd.isnull(df['vp'][d])):
        vp_string = (str(df.station[d]) + ' reported missing 5-minute vapor pressure data at ' + str(df.index[d]) + '\n')
        g.write(vp_string)
    elif(pd.isnull(df['sr'][d])):
        sr_string = (str(df.station[d]) + ' reported missing 5-minute solar radiation data at ' + str(df.index[d]) + '\n')
        g.write(sr_string)
    elif(pd.isnull(df['ws'][d])):
        ws_string = (str(df.station[d]) + ' reported missing 5-minute wind speed data at ' + str(df.index[d]) + '\n')
        g.write(ws_string)
    elif(pd.isnull(df['wind_vec'][d])):
        windvec_string = (str(df.station[d]) + ' reported missing 5-minute wind direction data at ' + str(df.index[d]) + '\n')
        g.write(windvec_string)
    elif(pd.isnull(df['pp'][d])):
        pp_string = (str(df.station[d]) + ' reported missing 5-minute precipitation data at ' + str(df.index[d]) + '\n')
        g.write(pp_string)
    elif(pd.isnull(df['st5'][d])):
        st5_string = (str(df.station[d]) + ' reported missing 5-minute st5 data at ' + str(df.index[d]) + '\n')
        g.write(st5_string)
    elif(pd.isnull(df['st15'][d])):
        st15_string = (str(df.station[d]) + ' reported missing 5-minute st15 data at ' + str(df.index[d]) + '\n')
        g.write(st15_string)
    elif(pd.isnull(df['gust'][d])):
        gust_string = (str(df.station[d]) + ' reported missing 5-minute gust data at ' + str(df.index[d]) + '\n')
        g.write(gust_string)
    elif(pd.isnull(df['gusttm'][d])):
        gusttm_string = (str(df.station[d]) + ' reported missing 5-minute gust time data at ' + str(df.index[d]) + '\n')
        g.write(gusttm_string)
    elif(pd.isnull(df['gustdir'][d])):
        gustdir_string = (str(df.station[d]) + ' reported missing 5-minute gust time data at ' + str(df.index[d]) + '\n')
        g.write(gustdir_string)
    d=d+1