In [1]:
import os
import pandas as pd
import numpy as np
import urllib
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [12]:
path = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC'
normpath = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\normals\normcomp'
maxpath = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\minimums\mincomp'
minpath = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\maximums\maxcomp'

os.chdir(path)

xl_file = r"C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\colocation_metadata.xlsx"
csv = r'C:\Users\student\Documents\Alistair CoAgMET Projects\Pythonstuff\QC\normals\COOP_Normals\csv.csv'

xl = pd.ExcelFile(xl_file)

meta = xl.parse('metadata')
meta['sdate'] = meta.sdate.dt.date
meta['edate'] = meta.edate.dt.date
meta.drop(meta.columns[3],axis=1)



urllib.request.urlretrieve(
    'http://coagmet.colostate.edu/cgi-bin/web_services.pl?type=daily&sids=akr02&sdate=1992-07-01&edate=2018-12-31&elems=tave,tmax,tmin,vp,rhmax,rhmin,sr,wrun,pp,st5mx,st5mn,st15mx,st15mn',
    filename=csv)
coag = pd.read_csv(csv)

coag = coag.reset_index()
coag.columns.values[0] = 'station'
coag.columns.values[1] = 'date'
coag.columns.values[2] = 'CoAg_tmean'
coag.columns.values[3] = 'CoAg_tmin'
coag.columns.values[4] = 'CoAg_tmax'
coag.columns.values[5] = 'vp'
coag.columns.values[6] = 'rhmax'
coag.columns.values[7] = 'rhmin'
coag.columns.values[8] = 'sr'
coag.columns.values[9] = 'wrun'
coag.columns.values[10] = 'pp'
coag.columns.values[11] = 'st5mx'
coag.columns.values[12] = 'st5mn'
coag.columns.values[13] = 'st15mx'
coag.columns.values[14] = 'st15mn'

stuff = ['vp','rhmax','rhmin','sr','wrun','pp','st5mx','st5mn','st15mx','st15mn']
coag = coag.drop(stuff, axis=1)
coag['date'] = pd.to_datetime(coag.date)
coag['julian'] = coag.date.dt.strftime('%j')
coag = coag[:-1]


coag_norm = coag.groupby(['julian']).mean().reset_index()
coag_max = coag.groupby(['julian']).max().reset_index()
coag_min = coag.groupby(['julian']).min().reset_index()

coag_norm.CoAg_tmax = 32 + (coag_norm.CoAg_tmax * (9.0/5.0))
coag_norm.CoAg_tmean = 32 + (coag_norm.CoAg_tmean * (9.0/5.0))
coag_norm.CoAg_tmin = 32 + (coag_norm.CoAg_tmin * (9.0/5.0))

coag_max.CoAg_tmean = 32 + (coag_max.CoAg_tmean * (9.0/5.0))
coag_max.CoAg_tmax = 32 + (coag_max.CoAg_tmax * (9.0/5.0))
coag_max.CoAg_tmin = 32 + (coag_max.CoAg_tmin * (9.0/5.0))

coag_min.CoAg_tmean = 32 + (coag_min.CoAg_tmean * (9.0/5.0))
coag_min.CoAg_tmax = 32 + (coag_min.CoAg_tmax * (9.0/5.0))
coag_min.CoAg_tmin = 32 + (coag_min.CoAg_tmin * (9.0/5.0))


urllib.request.urlretrieve(
    'http://data.rcc-acis.org/StnData?sid=050109&sdate=1992-07-01&edate=2018-12-31&elems=maxt,mint,avgt,pcpn&output=csv',
    filename=csv)

coop = pd.read_csv(csv)
coop = coop.reset_index()
coop.columns.values[0] = 'date'
coop.columns.values[1] = 'COOP_tmax'
coop.columns.values[2] = 'COOP_tmin'
coop.columns.values[3] = 'COOP_tmean'
coop.columns.values[4] = 'pcpn'
coop = coop.drop('pcpn', axis=1)

coop['date'] = pd.to_datetime(coop.date)
coop['julian'] = coop.date.dt.strftime('%j')

coop = coop.replace('M', np.nan, regex=True)
coop = coop.replace('T', 0.005, regex=True)

coop.COOP_tmax = coop.COOP_tmax.astype(float)
coop.COOP_tmin = coop.COOP_tmin.astype(float)
coop.COOP_tmean = coop.COOP_tmean.astype(float)


coop_norm = coop.groupby(['julian']).mean().reset_index()
coop_max = coop.groupby(['julian']).max().reset_index()
coop_min = coop.groupby(['julian']).min().reset_index()

df_norm = pd.merge(coag_norm,coop_norm, on=coag_norm.julian)
df_max = pd.merge(coag_max,coop_max,on=coag_max.julian)
df_min = pd.merge(coag_min,coop_min,on=coag_min.julian)

stuff = ['key_0','julian_y']

df_norm = df_norm.drop(stuff, axis=1)
df_max = df_max.drop(stuff, axis=1)
df_min = df_min.drop(stuff, axis=1)

df_norm = df_norm[['julian_x','CoAg_tmean','COOP_tmean','CoAg_tmax','COOP_tmax','CoAg_tmin','COOP_tmin']]
df_max = df_max[['julian_x','CoAg_tmean','COOP_tmean','CoAg_tmax','COOP_tmax','CoAg_tmin','COOP_tmin']]
df_min = df_min[['julian_x','CoAg_tmean','COOP_tmean','CoAg_tmax','COOP_tmax','CoAg_tmin','COOP_tmin']]

df_norm.columns.values[0] = 'julian_day'
df_max.columns.values[0] = 'julian_day'
df_min.columns.values[0] = 'julian_day'


df_norm

,julian_x,CoAg_tmean,COOP_tmean,CoAg_tmax,COOP_tmax,CoAg_tmin,COOP_tmin
0,001,16.418750,24.080000,6.161491,37.269231,31.373600,11.560000
1,002,23.876600,25.000000,16.771400,36.769231,44.449500,12.720000
2,003,24.424700,26.940000,17.191400,39.730769,43.847960,14.040000
3,004,22.505000,25.826923,11.431850,38.500000,37.274630,13.153846
4,005,23.856500,23.640000,11.010380,36.807692,39.210350,11.000000
5,006,26.794700,24.211538,7.833295,37.769231,37.765684,10.653846
6,007,25.960700,24.326923,12.725330,37.115385,39.153560,11.538462
7,008,30.460100,28.096154,15.851030,41.307692,41.961560,14.884615
8,009,31.152500,30.769231,15.128330,44.307692,40.035740,17.230769
9,010,31.785200,29.557692,16.869110,41.461538,41.547380,17.653846
10,011,27.371600,29.960000,13.962380,41.846154,42.181340,17.560000
11,012,26.667200,28.500000,10.801310,41.807692,34.686320,14.640000
12,013,28.790000,23.958333,13.020260,37.538462,39.181640,11.416667
13,014,31.032200,27.640000,15.953180,40.423077,41.922410,15.040000
14,015,27.381800,28.340000,16.481480,42.423077,44.096540,14.840000
15,016,27.308900,29.153846,15.730340,42.461538,40.936010,15.846154
16,017,29.032700,26.057692,12.794360,38.692308,40.289810,13.423077
17,018,34.229000,27.750000,16.520270,40.423077,47.048360,15.076923
18,019,35.572700,33.260000,19.130000,45.846154,46.505120,19.640000
19,020,32.318900,32.942308,18.477770,46.884615,42.871820,19.000000
20,021,29.952200,31.269231,17.518640,44.461538,44.980790,18.076923
21,022,29.563400,31.884615,15.785690,46.230769,43.274570,17.538462
22,023,32.234600,29.211538,14.305100,42.230769,43.258730,16.192308
23,024,31.989500,29.519231,15.970190,43.461538,43.901150,15.576923
24,025,32.552900,31.140000,17.631320,44.230769,44.381210,17.880000
25,026,31.316600,32.140000,16.327040,46.153846,44.489840,17.760000
26,027,33.194000,31.440000,17.694074,44.923077,42.457337,18.400000
27,028,35.102300,29.769231,16.868390,42.653846,43.774520,16.884615
28,029,36.722300,29.884615,17.262140,42.615385,43.486160,17.153846
29,030,37.607300,30.180000,17.498480,41.923077,44.977730,17.440000
...,...,...,...,...,...,...,...
336,337,32.706629,34.907407,19.418630,48.962963,47.428700,20.851852
337,338,31.457943,32.185185,16.111571,45.629630,44.447171,18.740741
338,339,31.764457,28.574074,12.264886,42.703704,38.294943,14.444444
339,340,31.145514,27.100000,11.931543,39.444444,39.965343,14.880000
340,341,30.228800,27.288462,13.661257,40.576923,36.943657,14.000000
341,342,31.641800,26.576923,13.384314,38.307692,41.842400,14.846154
342,343,31.577771,28.129630,14.378257,40.962963,42.447371,15.296296
343,344,34.148429,28.777778,15.818171,42.666667,45.303457,14.888889
344,345,34.363400,30.518519,16.281114,44.814815,46.855743,16.222222
345,346,34.530029,30.870370,18.378200,45.333333,49.333400,16.407407
346,347,31.946514,32.870370,21.099029,46.370370,47.532286,19.370370
347,348,29.325457,32.580000,19.070943,45.423077,45.223143,19.520000
348,349,27.920686,30.057692,13.287286,44.461538,41.088200,15.653846
349,350,28.972400,28.129630,15.050086,41.518519,41.529543,14.740741
350,351,26.479657,29.833333,14.891257,42.925926,38.814457,16.740741
351,352,25.854029,27.730769,13.175943,40.192308,39.995686,14.851852
352,353,28.943343,28.129630,13.089029,41.666667,37.430686,14.592593
353,354,32.575229,25.851852,12.794171,38.259259,40.076686,13.444444
354,355,32.068657,28.500000,13.847429,41.423077,39.351200,15.576923
355,356,30.557171,26.826923,12.365514,39.538462,37.350543,14.115385
356,357,28.096314,24.750000,12.295400,36.230769,36.462457,12.333333
357,358,26.731400,24.692308,10.830971,37.538462,37.741400,11.846154
358,359,29.434229,24.180000,13.039486,38.038462,40.175771,10.360000
359,360,23.118029,27.166667,12.764343,40.148148,38.750429,14.185185
360,361,21.335514,25.611111,11.560657,39.037037,39.068171,12.185185
361,362,23.303171,26.480769,13.849571,39.423077,39.430400,13.538462
362,363,23.548229,27.365385,14.153857,40.653846,39.911514,14.076923
363,364,20.624771,28.380000,12.627800,40.730769,38.672771,15.200000
364,365,13.836560,27.444444,9.200300,39.814815,34.503050,15.074074
365,366,38.472800,30.500000,15.082400,45.714286,40.920800,15.285714